exclude: [config.ru, Gemfile, Gemfile.lock, Procfile, Rakefile, README.md, vendor, LICENSE.txt]

# Site settings
name: 'Andrew Atkinson'
title: 'Software Engineer, Author, High Performance PostgreSQL for Rails'
tagline: "Andrew Atkinson's site about PostgreSQL, Ruby on Rails, Elasticsearch, Kubernetes, and Vim. Andrew is the Author of High Performance PostgreSQL for Rails"
description: 'Software Engineer, Author, Consultant'
meta_description: 'Personal Site Andrew Atkinson. PostgreSQL. Ruby on Rails, Elasticsearch, Kubernetes, Vim. Author High Performance PostgreSQL for Rails Pragmatic Programmers'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'authorimagenew.jpg'
  greetings: 'Hi! My name is Andy and this is my website, blog and portfolio. Please take a look around and thanks for stopping by!'
favicon: 'assets/images/favicon.ico'
baseurl:
url: https://andyatkinson.com
production_url: https://andyatkinson.com
mailchimp_url: 'https://gmail.us3.list-manage.com/subscribe/post?u=e41bf915471ba36d210444e0d&amp;id=d5e090a16c'
ga_analytics: UA-8656956-2
works_for: Refined Pages, LLC

# Contact form setings
email: andyatkinson@gmail.com
contact_page_description: "Send me a message!"
thankyou_page_description: "Thanks for your message."

# Social links
social:
  name: Andrew Atkinson
  links:
    - https://www.linkedin.com/in/andyatkinson
    - https://github.com/andyatkinson
github: 'andyatkinson'
linkedin: 'andyatkinson'
stackoverflow: '126688/andy-atkinson?tab=profile'
bluesky:
  username: andyatkinson.com

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Consulting
    url: /consulting
  - text: Book
    url: /pgrailsbook
  - text: Speaking
    url: /speaking-opportunities
  - text: Writing
    url: /writing
  - text: Ruby on Rails
    url: /rails-tips
  - text: PostgreSQL
    url: /postgresql-tips
  - text: Extra
    url: /extra
  - text: Archive
    url: /tag
  - text: Contact Me
    url: /contact

# Required Plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Pagination
paginate: 10
paginate_path: /page:num/

# Permalinks
permalink: /blog/:year/:month/:day/:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed

# disable Rouge https://mycyberuniverse.com/disable-rouge-syntax-highlighter.html
# https://jordanknott.com/blog/2017-04-6-better-jekyll-syntax-highlighting-with-prism/
highlighter: none

feed:
  tags: true
