name: Andy Atkinson
description: Software development tech blog
meta_description: "Tips, tutorials, and interesting software engineering tidbits from Andy Atkinson"

exclude: [config.ru, Gemfile, Gemfile.lock, Procfile, Rakefile, README.md, vendor, LICENSE.txt]

markdown: redcarpet
redcarpet:
  extensions: [footnotes]
highlighter: true
logo: false
paginate: 25

# Details for the RSS feed generator
url:            'http://andyatkinson.com'
author:         'Andy Atkinson'

permalink: /blog/:year/:month/:day/:title
