exclude: [config.ru, Gemfile, Gemfile.lock, Procfile, Rakefile, README.md, vendor, LICENSE.txt]

# Site setings
name: 'Andy Atkinson'
description: 'Software Engineer'
meta_description: 'Personal website of Andy Atkinson covering software development tips, tools, open source, events, and a project portfolio'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'authorimage.jpg'
  greetings: 'Hi! My name is Andy and this is my website, blog and portfolio. Please take a look around and thanks for stopping by!'
favicon: 'assets/images/favicon.ico'
baseurl:
production_url: http://andyatkinson.com
disqus: 'andyatkinson'
mailchimp_url: 'https://gmail.us3.list-manage.com/subscribe/post?u=e41bf915471ba36d210444e0d&amp;id=d5e090a16c'
# Add your GA Tracking Id
ga_analytics: UA-8656956-2

# Contact form setings
email: andyatkinson@gmail.com
contact_page_description: "Send me a message with questions, concerns or tips!"
thankyou_page_description: "Thanks for your message."

# Social links
#twitter: 'andatki'
github: 'andyatkinson'
linkedin: 'andyatkinson'
stackoverflow: '126688/andy-atkinson?tab=profile'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Projects
    url: /projects
  - text: Open Source
    url: /open-source
  - text: Writing
    url: /writing
  - text: Speaking
    url: /speaking-opportunities
  - text: Events
    url: /events-and-volunteering
  - text: PostgreSQL
    url: /postgresql-tips
  - text: Ruby on Rails
    url: /rails-tips
  - text: Archive
    url: /tag
  - text: Contact Me
    url: /contact

# Required Plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 10
paginate_path: /page:num/

# Permalinks
permalink: /blog/:year/:month/:day/:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed

# disable Rouge https://mycyberuniverse.com/disable-rouge-syntax-highlighter.html
# https://jordanknott.com/blog/2017-04-6-better-jekyll-syntax-highlighting-with-prism/
highlighter: none
